<?php

namespace ContainerLB1KPLw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectGameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProjectGame' shared autowired service.
     *
     * @return \App\Controller\ProjectGame
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProjectGame.php';

        $container->services['App\\Controller\\ProjectGame'] = $instance = new \App\Controller\ProjectGame();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ProjectGame', $container));

        return $instance;
    }
}
