<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5xEgpN\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5xEgpN/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerW5xEgpN.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerW5xEgpN\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerW5xEgpN\App_KernelTestDebugContainer([
    'container.build_hash' => 'W5xEgpN',
    'container.build_id' => 'eb8d2de0',
    'container.build_time' => 1717854520,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5xEgpN');
