<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEcfVf8\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEcfVf8/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXEcfVf8.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXEcfVf8\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXEcfVf8\App_KernelTestDebugContainer([
    'container.build_hash' => 'XEcfVf8',
    'container.build_id' => '9198b8e1',
    'container.build_time' => 1717242883,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEcfVf8');
