<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF7aUXD7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF7aUXD7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF7aUXD7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF7aUXD7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF7aUXD7\App_KernelDevDebugContainer([
    'container.build_hash' => 'F7aUXD7',
    'container.build_id' => '7810d592',
    'container.build_time' => 1717487399,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF7aUXD7');
