<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLYpvvqp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLYpvvqp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLYpvvqp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLYpvvqp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLYpvvqp\App_KernelDevDebugContainer([
    'container.build_hash' => 'LYpvvqp',
    'container.build_id' => '12d63125',
    'container.build_time' => 1717502329,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLYpvvqp');
